### ISSUE TITLE
How to compile and run this example today?

### ISSUE THREAD

**Issue by simonhf** [davecheney/ccode#1]
Hello! I tried building the example today (June 2021) with the command line in the blog, but could not get it to work:

```
$ go version
go version go1.16.3 darwin/amd64
$ GO111MODULE="off" go test -v
package .: C source files not allowed when not using cgo or SWIG: ccode.c
```

Is this code still a thing? And how to compile it? Or would it have to be wrapped in cgo these days?

**Comment by davecheney** [comment]
The facility for this was removed around go 1.4
